name: flim
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=1.0.0
  - altair=5.4.1
  - annotated-types=0.7.0
  - aom=3.9.1
  - app-model=0.3.0
  - appdirs=1.4.4
  - appnope=0.1.4
  - asciitree=0.3.3
  - asttokens=2.4.1
  - attrs=24.2.0
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.0
  - aws-c-common=0.10.3
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.1
  - aws-c-io=0.15.2
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.1
  - aws-c-sdkutils=0.2.1
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.4
  - aws-sdk-cpp=1.11.449
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.16.0
  - blinker=1.9.0
  - blosc=1.21.6
  - bokeh=3.6.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.3
  - c-blosc2=2.15.1
  - ca-certificates=2024.8.30
  - cachetools=5.5.0
  - cachey=0.2.1
  - cairo=1.18.0
  - cellpose=3.0.11
  - certifi=2024.8.30
  - cffi=1.17.1
  - charls=2.4.2
  - charset-normalizer=3.4.0
  - click=8.1.7
  - cloudpickle=3.1.0
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.1
  - cpython=3.12.7
  - cycler=0.12.1
  - cytoolz=1.0.1
  - dask=2024.12.0
  - dask-core=2024.12.0
  - dask-expr=1.1.20
  - dask-image=2024.5.3
  - dav1d=1.2.1
  - debugpy=1.8.8
  - decorator=5.1.1
  - distributed=2024.12.0
  - docstring_parser=0.16
  - docutils=0.21.2
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fasteners=0.17.3
  - fastremap=1.14.0
  - ffmpeg=7.1.0
  - filelock=3.16.1
  - flexcache=0.3
  - flexparser=0.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.54.1
  - freetype=2.12.1
  - freetype-py=2.5.1
  - fribidi=1.0.10
  - fsspec=2024.10.0
  - gdk-pixbuf=2.42.12
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.11
  - gitpython=3.1.43
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - graphite2=1.3.13
  - h2=4.1.0
  - harfbuzz=9.0.0
  - hdf5=1.14.4
  - heapdict=1.0.1
  - hpack=4.0.0
  - hsluv=5.0.4
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - imagecodecs=2024.9.22
  - imageio=2.36.0
  - imagesize=1.4.1
  - imath=3.1.12
  - importlib-metadata=7.2.1
  - importlib_resources=6.4.5
  - in-n-out=0.2.1
  - ipykernel=6.29.5
  - ipython=8.29.0
  - ipywidgets=8.1.5
  - jasper=4.2.4
  - jedi=0.19.2
  - jinja2=3.1.4
  - joblib=1.4.2
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyterlab_widgets=3.0.13
  - jxrlib=1.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libarrow=18.0.0
  - libarrow-acero=18.0.0
  - libarrow-dataset=18.0.0
  - libarrow-substrait=18.0.0
  - libasprintf=0.22.5
  - libass=0.17.3
  - libavif16=1.1.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.10.1
  - libcxx=19.1.3
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgettextpo=0.22.5
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.82.2
  - libgoogle-cloud=2.31.0
  - libgoogle-cloud-storage=2.31.0
  - libgrpc=1.67.1
  - libhwloc=2.11.2
  - libhwy=1.1.0
  - libiconv=1.17
  - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - libjxl=0.11.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.64.0
  - libopenblas=0.3.28
  - libopencv=4.10.0
  - libopenvino=2024.4.0
  - libopenvino-arm-cpu-plugin=2024.4.0
  - libopenvino-auto-batch-plugin=2024.4.0
  - libopenvino-auto-plugin=2024.4.0
  - libopenvino-hetero-plugin=2024.4.0
  - libopenvino-ir-frontend=2024.4.0
  - libopenvino-onnx-frontend=2024.4.0
  - libopenvino-paddle-frontend=2024.4.0
  - libopenvino-pytorch-frontend=2024.4.0
  - libopenvino-tensorflow-frontend=2024.4.0
  - libopenvino-tensorflow-lite-frontend=2024.4.0
  - libopus=1.3.1
  - libparquet=18.0.0
  - libpng=1.6.44
  - libprotobuf=5.28.2
  - libre2-11=2024.07.02
  - librsvg=2.58.4
  - libsodium=1.0.20
  - libsqlite=3.47.0
  - libssh2=1.11.0
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libutf8proc=2.8.0
  - libuv=1.49.2
  - libvpx=1.14.1
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxml2=2.13.4
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - llvm-openmp=19.1.3
  - llvmlite=0.43.0
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - magicgui=0.9.1
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.1.0
  - munkres=1.1.4
  - napari=0.5.5
  - napari-base=0.5.5
  - napari-console=0.1.2
  - napari-plugin-engine=0.2.0
  - napari-plugin-manager=0.1.3
  - napari-svg=0.2.0
  - narwhals=1.14.0
  - natsort=8.4.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nomkl=1.0
  - npe2=0.7.7
  - numba=0.60.0
  - numcodecs=0.13.1
  - numpy=1.26.4
  - numpydoc=1.8.0
  - opencv=4.10.0
  - openexr=3.3.1
  - openh264=2.5.0
  - openjpeg=2.5.2
  - openssl=3.4.0
  - orc=2.0.3
  - packaging=24.1
  - pandas=2.2.3
  - pango=1.54.0
  - parso=0.8.4
  - partd=1.4.2
  - patsy=1.0.1
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pims=0.7
  - pint=0.24.4
  - pip=24.3.1
  - pixman=0.43.4
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - plotly=5.24.1
  - pooch=1.8.2
  - prompt-toolkit=3.0.48
  - protobuf=5.28.2
  - psutil=6.1.0
  - psygnal=0.11.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pure_eval=0.2.3
  - py-opencv=4.10.0
  - pyarrow=18.0.0
  - pyarrow-core=18.0.0
  - pyconify=0.1.6
  - pycparser=2.22
  - pydantic=2.10.3
  - pydantic-compat=0.1.2
  - pydantic-core=2.27.1
  - pydeck=0.8.0
  - pygments=2.18.0
  - pynndescent=0.5.13
  - pyopengl=3.1.6
  - pyparsing=3.2.0
  - pyproject_hooks=1.2.0
  - pyqtgraph=0.13.7
  - pysocks=1.7.1
  - python=3.12.7
  - python-build=1.2.2.post1
  - python-dateutil=2.9.0
  - python-dotenv=1.0.1
  - python-tzdata=2024.2
  - python_abi=3.12
  - pytorch=2.5.1
  - pytz=2024.1
  - pywavelets=1.7.0
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - qtconsole-base=5.6.1
  - qtpy=2.4.2
  - rav1e=0.6.6
  - re2=2024.07.02
  - read-roi=1.6.0
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rich=13.9.4
  - roifile=2024.5.24
  - rpds-py=0.21.0
  - scikit-image=0.24.0
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - sdtfile=2024.11.24
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.3.0
  - shellingham=1.5.4
  - six=1.16.0
  - sleef=3.7
  - slicerator=1.1.0
  - smmap=5.0.0
  - snappy=1.2.1
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - sphinx=8.1.3
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - stack_data=0.6.2
  - statannotations=0.7.1
  - statsmodels=0.14.4
  - streamlit=1.40.1
  - superqt=0.6.7
  - svt-av1=2.3.0
  - sympy=1.13.3
  - tabulate=0.9.0
  - tbb=2022.0.0
  - tblib=3.0.0
  - tenacity=9.0.0
  - threadpoolctl=3.5.0
  - tifffile=2024.9.20
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - tomli-w=1.1.0
  - toolz=1.0.0
  - tornado=6.4.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typer=0.15.1
  - typer-slim=0.15.1
  - typer-slim-standard=0.15.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - tzlocal=5.2
  - umap-learn=0.5.7
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - validators=0.34.0
  - vispy=0.14.3
  - watchdog=6.0.0
  - wcwidth=0.2.13
  - wheel=0.45.0
  - widgetsnbextension=4.0.13
  - wrapt=1.17.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xyzservices=2024.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - zarr=2.18.4
  - zeromq=4.3.5
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.21.0
  - zlib=1.3.1
  - zlib-ng=2.2.2
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - cell-analysis-tools==1.0.1
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.15
      - pyqt5-sip==12.15.0
      - streamlit-plotly-events==0.0.6
