[channel_name]
ch1 = "nadh"
ch2 = "fad"
ch3 = "red"

[file_suffix]
ch1_mask = "_photons_cellpose.tiff"
ch1_irf = "nad_irf.txt"
ch1_decay = "n.sdt"
ch1_histogram = "_ch1.csv"
ch1_a1 = "n_a1[%].asc"
green_irf = "fad_irf.txt"
green_decay = "f.sdt"
green_histogram = "_ch2.csv"
green_a1 = "f_a1[%].asc"
red_irf = "red_irf.txt"
red_decay = "r.sdt"
red_histogram = "_ch3.csv"
red_a1 = "r_a1[%].asc"
