"""Predict the feature columns a configured extraction profile will emit.

Use selected extractors and per-channel settings to supply derived-feature operand
choices before extraction runs. Names must match ``src/fov_extraction.py``:

* **categorized** — ``"{Extractor}_{channel}: {suffix}"`` from
  ``predict_feature_columns()``.
* **uncategorized** — ``"{channel}_{suffix}"``, no extractor prefix: the fit's
  bookkeeping (``amp1``, ``offset``, ``reduced_chi_square``, the ``a2``/``a3``
  remainders) and the morphology centroids. ``predict_uncategorized_columns()``.

Uncategorized columns follow categorized columns in the operand list.
"""

# Fixed per-extractor categorized suffixes. "Lifetime fit" is component-count
# dependent, so it is generated by _fit_suffixes() rather than listed here.
EXTRACTOR_FEATURE_SUFFIXES = {
    "Lifetime fit free": [
        "G(1st)", "S(1st)", "Tau_phase", "Tau_mod", "G(2nd)", "S(2nd)",
    ],
    "Intensity morphology": [
        "area", "perimeter", "solidity", "eccentricity",
        "major_axis_length", "minor_axis_length", "circularity",
    ],
    "Intensity texture": [
        "intensity_sum",
        "granularity_1", "granularity_3", "granularity_5", "granularity_7",
        "radial_distribution_ring1", "radial_distribution_ring2",
        "radial_distribution_ring3", "radial_distribution_ring4",
        "mass_displacement",
    ],
}

# Fixed per-extractor *uncategorized* suffixes. "Lifetime fit" depends on the
# component count and the input type, so it is generated by
# _fit_uncategorized_suffixes(); "Lifetime fit free" and "Intensity texture"
# emit none.
UNCATEGORIZED_SUFFIXES = {
    "Intensity morphology": ["centroid_x", "centroid_y"],
}


def _component_count(num_components):
    """Coerce a configured component count into the supported 1–3 range."""
    try:
        n = int(num_components)
    except (TypeError, ValueError):
        n = 1
    return max(1, min(n, 3))


def _fit_suffixes(num_components):
    """Categorized suffixes emitted by the 'Lifetime fit' extractor.

    For both fitted and SPCImage inputs, emit ``t1..tn``; add ``a1..a(n-1)``,
    ``tm`` and ``tm_iw`` when n >= 2. Clamp n to the supported 1–3 range.
    """
    n = _component_count(num_components)
    suffixes = [f"t{i}" for i in range(1, n + 1)]
    if n >= 2:
        suffixes += [f"a{i}" for i in range(1, n)]
        suffixes += ["tm", "tm_iw"]
    return suffixes


def _fit_uncategorized_suffixes(num_components, prefitted=False):
    """Uncategorized suffixes emitted by the 'Lifetime fit' extractor.

    Fitted inputs emit ``amp1..ampn``, ``offset``, and ``reduced_chi_square``.
    Both fitted and SPCImage inputs emit the remaining fraction ``a{n}`` when
    n >= 2; SPCImage inputs emit no other uncategorized fit columns.
    """
    n = _component_count(num_components)
    if prefitted:
        return [f"a{n}"] if n >= 2 else []
    suffixes = ["amp1", "offset", "reduced_chi_square"]
    suffixes += [f"amp{i}" for i in range(2, n + 1)]
    if n >= 2:
        suffixes.append(f"a{n}")
    return suffixes


def predict_feature_columns(channel_names, selected_extractors, num_components, input_types=None):
    """Predict the categorized feature columns a profile will produce.

    Args:
        channel_names: iterable of channel display names.
        selected_extractors: dict ``{channel_name: [extractor, ...]}``.
        num_components: dict ``{channel_name: int}`` (only read for 'Lifetime fit').
        input_types: optional dict ``{channel_name: input_type}``. Only consulted to
            narrow 'Intensity texture' on a 'Decay (2D)' channel to ``intensity_sum``.
            A 2D CSV has no image or mask. Omitting input_types, or supplying a
            non-2D input type, yields the full suffix list.

    Returns:
        Ordered list of unique ``"{Extractor}_{channel}: {suffix}"`` column names.
    """
    input_types = input_types or {}
    columns = []
    for channel_name in channel_names:
        extractors = selected_extractors.get(channel_name, []) or []
        for extractor in extractors:
            if extractor == "Lifetime fit":
                suffixes = _fit_suffixes(num_components.get(channel_name, 1))
            elif extractor == "Intensity texture" and input_types.get(channel_name) == "Decay (2D)":
                suffixes = ["intensity_sum"]
            else:
                suffixes = EXTRACTOR_FEATURE_SUFFIXES.get(extractor, [])
            for suffix in suffixes:
                col = f"{extractor}_{channel_name}: {suffix}"
                if col not in columns:
                    columns.append(col)
    return columns


def predict_uncategorized_columns(channel_names, selected_extractors, num_components, input_types=None):
    """Predict the uncategorized (extractor-prefix-less) columns a profile will produce.

    Same arguments as :func:`predict_feature_columns`. ``input_types`` affects
    'Lifetime fit': SPCImage inputs emit only ``a{n}`` when n >= 2.

    Returns:
        Ordered list of unique ``"{channel}_{suffix}"`` column names.
    """
    input_types = input_types or {}
    columns = []
    for channel_name in channel_names:
        extractors = selected_extractors.get(channel_name, []) or []
        for extractor in extractors:
            if extractor == "Lifetime fit":
                suffixes = _fit_uncategorized_suffixes(
                    num_components.get(channel_name, 1),
                    prefitted="prefitted" in (input_types.get(channel_name) or ""),
                )
            else:
                suffixes = UNCATEGORIZED_SUFFIXES.get(extractor, [])
            for suffix in suffixes:
                col = f"{channel_name}_{suffix}"
                if col not in columns:
                    columns.append(col)
    return columns


def _profile_channels(cfg):
    """Unpack an active-profile config dict into the four per-channel arguments.

    Reads the per-channel structure written by the Configuration page
    (``main.py``): channel display name, selected input type, selected feature
    extractors, and (for Lifetime fit) the component count. Returned in the
    positional order both ``predict_*_columns`` functions take.
    """
    num_channels = cfg.get("num_channels", 0)
    channel_names = []
    selected_extractors = {}
    num_components = {}
    input_types = {}
    for i in range(num_channels):
        channel_key = f"ch{i + 1}"
        ch_cfg = cfg.get(channel_key, {})
        channel_name = ch_cfg.get("channel_name", channel_key)
        input_type = ch_cfg.get("input_type")
        input_cfg = ch_cfg.get(input_type, {}) if input_type else {}
        channel_names.append(channel_name)
        selected_extractors[channel_name] = input_cfg.get("selected_feature_extractors", [])
        num_components[channel_name] = input_cfg.get("num_components", 1)
        input_types[channel_name] = input_type
    return channel_names, selected_extractors, num_components, input_types


def predict_feature_columns_from_cfg(cfg, include_uncategorized=False):
    """Predict columns from an active-profile config dict.

    With *include_uncategorized*, append uncategorized columns after categorized ones.
    """
    channels = _profile_channels(cfg)
    columns = predict_feature_columns(*channels)
    if include_uncategorized:
        columns += predict_uncategorized_columns(*channels)
    return columns
