"""Predict the feature columns a configured extraction profile will emit.

Derived features (``src/derived_features.py``) let a user build new columns from
arithmetic over *existing* extracted features. To offer sensible operand choices
at config time — before any extraction has run — we predict which columns the
current profile will produce, from its selected extractors and per-channel
settings alone.

The prediction mirrors the naming convention in ``src/fov_extraction.py``, which
emits two kinds of column:

* **categorized** — ``"{Extractor}_{channel}: {suffix}"``, the measurements
  proper. ``predict_feature_columns()``.
* **uncategorized** — ``"{channel}_{suffix}"``, no extractor prefix: the fit's
  bookkeeping (``amp1``, ``offset``, ``reduced_chi_square``, the ``a2``/``a3``
  remainders) and the morphology centroids. ``predict_uncategorized_columns()``.

Data Analysis files the second kind under "Uncategorized Features", but they are
ordinary per-cell numbers, so they are offered as derived-feature operands too —
a background-corrected intensity is ``intensity_sum - offset * time_bins``. They
are listed *after* the categorized columns, which are what most formulas want.
"""

# Fixed per-extractor categorized suffixes. "Lifetime fit" is component-count
# dependent, so it is generated by _fit_suffixes() rather than listed here.
EXTRACTOR_FEATURE_SUFFIXES = {
    "Lifetime fit free": [
        "G(1st)", "S(1st)", "Tau_phase", "Tau_mod", "G(2nd)", "S(2nd)",
    ],
    "Intensity morphology": [
        "area", "perimeter", "solidity", "eccentricity",
        "major_axis_length", "minor_axis_length", "circularity",
    ],
    "Intensity texture": [
        "intensity_sum",
        "granularity_1", "granularity_3", "granularity_5", "granularity_7",
        "radial_distribution_ring1", "radial_distribution_ring2",
        "radial_distribution_ring3", "radial_distribution_ring4",
        "mass_displacement",
    ],
}

# Fixed per-extractor *uncategorized* suffixes. "Lifetime fit" depends on the
# component count and the input type, so it is generated by
# _fit_uncategorized_suffixes(); "Lifetime fit free" and "Intensity texture"
# emit none.
UNCATEGORIZED_SUFFIXES = {
    "Intensity morphology": ["centroid_x", "centroid_y"],
}


def _component_count(num_components):
    """Coerce a configured component count into the supported 1–3 range."""
    try:
        n = int(num_components)
    except (TypeError, ValueError):
        n = 1
    return max(1, min(n, 3))


def _fit_suffixes(num_components):
    """Categorized suffixes emitted by the 'Lifetime fit' extractor.

    Mirrors ``extract_fit_results`` *and* ``extract_spcimage_fit_results``, which
    agree here: ``t1..tn`` for all n; plus ``a1..a(n-1)``, ``tm`` and ``tm_iw``
    when n >= 2 (the multi-exponential case). Clamped to the supported 1–3
    component range. The prefitted split lives in ``_fit_uncategorized_suffixes``
    alone — the categorized names do not depend on the input type.
    """
    n = _component_count(num_components)
    suffixes = [f"t{i}" for i in range(1, n + 1)]
    if n >= 2:
        suffixes += [f"a{i}" for i in range(1, n)]
        suffixes += ["tm", "tm_iw"]
    return suffixes


def _fit_uncategorized_suffixes(num_components, prefitted=False):
    """Uncategorized suffixes emitted by the 'Lifetime fit' extractor.

    Mirrors ``extract_fit_results``: the raw amplitudes ``amp1..ampn``, the fitted
    background ``offset``, ``reduced_chi_square``, and the ``a{n}`` remainder that
    completes the ``a1``(``a2``) percentages when n >= 2. A pixel-prefitted
    (SPCImage) channel re-reads someone else's per-pixel fit, so it emits only
    that remainder — mirrors ``extract_spcimage_fit_results``.
    """
    n = _component_count(num_components)
    if prefitted:
        return [f"a{n}"] if n >= 2 else []
    suffixes = ["amp1", "offset", "reduced_chi_square"]
    suffixes += [f"amp{i}" for i in range(2, n + 1)]
    if n >= 2:
        suffixes.append(f"a{n}")
    return suffixes


def predict_feature_columns(channel_names, selected_extractors, num_components, input_types=None):
    """Predict the categorized feature columns a profile will produce.

    Args:
        channel_names: iterable of channel display names.
        selected_extractors: dict ``{channel_name: [extractor, ...]}``.
        num_components: dict ``{channel_name: int}`` (only read for 'Lifetime fit').
        input_types: optional dict ``{channel_name: input_type}``. Only consulted to
            narrow 'Intensity texture' on a 'Decay (2D)' channel to ``intensity_sum``.
            Mirrors the 2D special case in
            ``fov_extraction.extract_intensity_features``: a 2D CSV has no image/mask,
            so ``intensity_sum`` (the decay-curve sum) is the only texture feature it
            can emit. Omitting it (or a non-2D value) yields the full suffix list.

    Returns:
        Ordered list of unique ``"{Extractor}_{channel}: {suffix}"`` column names.
    """
    input_types = input_types or {}
    columns = []
    for channel_name in channel_names:
        extractors = selected_extractors.get(channel_name, []) or []
        for extractor in extractors:
            if extractor == "Lifetime fit":
                suffixes = _fit_suffixes(num_components.get(channel_name, 1))
            elif extractor == "Intensity texture" and input_types.get(channel_name) == "Decay (2D)":
                suffixes = ["intensity_sum"]
            else:
                suffixes = EXTRACTOR_FEATURE_SUFFIXES.get(extractor, [])
            for suffix in suffixes:
                col = f"{extractor}_{channel_name}: {suffix}"
                if col not in columns:
                    columns.append(col)
    return columns


def predict_uncategorized_columns(channel_names, selected_extractors, num_components, input_types=None):
    """Predict the uncategorized (extractor-prefix-less) columns a profile will produce.

    Same arguments as :func:`predict_feature_columns`. ``input_types`` is consulted
    for 'Lifetime fit' only: a pixel-prefitted channel emits just the ``a{n}``
    remainder, having done no fit of its own.

    Returns:
        Ordered list of unique ``"{channel}_{suffix}"`` column names.
    """
    input_types = input_types or {}
    columns = []
    for channel_name in channel_names:
        extractors = selected_extractors.get(channel_name, []) or []
        for extractor in extractors:
            if extractor == "Lifetime fit":
                suffixes = _fit_uncategorized_suffixes(
                    num_components.get(channel_name, 1),
                    prefitted="prefitted" in (input_types.get(channel_name) or ""),
                )
            else:
                suffixes = UNCATEGORIZED_SUFFIXES.get(extractor, [])
            for suffix in suffixes:
                col = f"{channel_name}_{suffix}"
                if col not in columns:
                    columns.append(col)
    return columns


def _profile_channels(cfg):
    """Unpack an active-profile config dict into the four per-channel arguments.

    Reads the per-channel structure written by the Configuration page
    (``main.py``): channel display name, selected input type, selected feature
    extractors, and (for Lifetime fit) the component count. Returned in the
    positional order both ``predict_*_columns`` functions take.
    """
    num_channels = cfg.get("num_channels", 0)
    channel_names = []
    selected_extractors = {}
    num_components = {}
    input_types = {}
    for i in range(num_channels):
        channel_key = f"ch{i + 1}"
        ch_cfg = cfg.get(channel_key, {})
        channel_name = ch_cfg.get("channel_name", channel_key)
        input_type = ch_cfg.get("input_type")
        input_cfg = ch_cfg.get(input_type, {}) if input_type else {}
        channel_names.append(channel_name)
        selected_extractors[channel_name] = input_cfg.get("selected_feature_extractors", [])
        num_components[channel_name] = input_cfg.get("num_components", 1)
        input_types[channel_name] = input_type
    return channel_names, selected_extractors, num_components, input_types


def predict_feature_columns_from_cfg(cfg, include_uncategorized=False):
    """Convenience adapter: predict columns from an active-profile config dict.

    With *include_uncategorized*, the profile's uncategorized bookkeeping columns
    are appended *after* the categorized ones, so the measurements stay at the top
    of an operand picker (see the module docstring).
    """
    channels = _profile_channels(cfg)
    columns = predict_feature_columns(*channels)
    if include_uncategorized:
        columns += predict_uncategorized_columns(*channels)
    return columns
