"""Predict the categorized feature columns a configured extraction profile will emit.

Derived features (``src/derived_features.py``) let a user build new columns from
arithmetic over *existing* extracted features. To offer sensible operand choices
at config time — before any extraction has run — we predict which categorized
columns the current profile will produce, from its selected extractors and
per-channel component counts alone.

The prediction mirrors the naming convention in ``src/fov_extraction.py``:
categorized columns are ``"{Extractor}_{channel}: {suffix}"``. Uncategorized
bookkeeping columns (``amp1``, ``offset``, ``reduced_chi_square``,
``centroid_x``/``centroid_y``, and the ``a2``/``a3`` fit remainders) are
intentionally excluded — they are not the intended operands for derived features.
"""

# Fixed per-extractor categorized suffixes. "Lifetime fit" is component-count
# dependent, so it is generated by _fit_suffixes() rather than listed here.
EXTRACTOR_FEATURE_SUFFIXES = {
    "Lifetime fit free": [
        "G(1st)", "S(1st)", "Tau_phase", "Tau_mod", "G(2nd)", "S(2nd)",
    ],
    "Intensity morphology": [
        "area", "perimeter", "solidity", "eccentricity",
        "major_axis_length", "minor_axis_length", "circularity",
    ],
    "Intensity texture": [
        "intensity_sum",
        "granularity_1", "granularity_3", "granularity_5", "granularity_7",
        "radial_distribution_ring1", "radial_distribution_ring2",
        "radial_distribution_ring3", "radial_distribution_ring4",
        "mass_displacement",
    ],
}


def _fit_suffixes(num_components):
    """Categorized suffixes emitted by the 'Lifetime fit' extractor.

    Mirrors ``extract_fit_results``/``extract_spcimage_fit_results``: ``t1..tn``
    for all n; plus ``a1..a(n-1)``, ``tm`` and ``tm_iw`` when n >= 2 (the
    multi-exponential case). Clamped to the supported 1–3 component range.
    """
    try:
        n = int(num_components)
    except (TypeError, ValueError):
        n = 1
    n = max(1, min(n, 3))
    suffixes = [f"t{i}" for i in range(1, n + 1)]
    if n >= 2:
        suffixes += [f"a{i}" for i in range(1, n)]
        suffixes += ["tm", "tm_iw"]
    return suffixes


def predict_feature_columns(channel_names, selected_extractors, num_components):
    """Predict the categorized feature columns a profile will produce.

    Args:
        channel_names: iterable of channel display names.
        selected_extractors: dict ``{channel_name: [extractor, ...]}``.
        num_components: dict ``{channel_name: int}`` (only read for 'Lifetime fit').

    Returns:
        Ordered list of unique ``"{Extractor}_{channel}: {suffix}"`` column names.
    """
    columns = []
    for channel_name in channel_names:
        extractors = selected_extractors.get(channel_name, []) or []
        for extractor in extractors:
            if extractor == "Lifetime fit":
                suffixes = _fit_suffixes(num_components.get(channel_name, 1))
            else:
                suffixes = EXTRACTOR_FEATURE_SUFFIXES.get(extractor, [])
            for suffix in suffixes:
                col = f"{extractor}_{channel_name}: {suffix}"
                if col not in columns:
                    columns.append(col)
    return columns


def predict_feature_columns_from_cfg(cfg):
    """Convenience adapter: predict columns from an active-profile config dict.

    Reads the per-channel structure written by the Configuration page
    (``main.py``): channel display name, selected input type, selected feature
    extractors, and (for Lifetime fit) the component count.
    """
    num_channels = cfg.get("num_channels", 0)
    channel_names = []
    selected_extractors = {}
    num_components = {}
    for i in range(num_channels):
        channel_key = f"ch{i + 1}"
        ch_cfg = cfg.get(channel_key, {})
        channel_name = ch_cfg.get("channel_name", channel_key)
        input_type = ch_cfg.get("input_type")
        input_cfg = ch_cfg.get(input_type, {}) if input_type else {}
        channel_names.append(channel_name)
        selected_extractors[channel_name] = input_cfg.get("selected_feature_extractors", [])
        num_components[channel_name] = input_cfg.get("num_components", 1)
    return predict_feature_columns(channel_names, selected_extractors, num_components)
