[server]
headless = false
enableStaticServing = false
runOnSave = true
fileWatcherType = "poll"

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[global]
developmentMode = false

[client]
showErrorDetails = false 